services:
  mysql:
    image: mysql:8

    container_name: mysql-container

    environment:
      MYSQL_ROOT_PASSWORD: atavrat13
      MYSQL_DATABASE: onlineshopping6


    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10



  app:
    image: hayruncelik692/devopssssss-app:latest
    build: .
    container_name: devopssssss-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mynet
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/onlineshopping6?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: atavrat13


networks:
  mynet:
    driver: bridge
    name: mynet

volumes:
  mysql_data:
